const questions = [
  "Do you have an incurable STD? (Herpes, HIV, AIDS)",
  "Do you have daddy issues? (Absentee / no father in childhood)",
  "Did you not get your high school diploma?",
  "Are you foul-mouthed?",
  "Are you a heavy drug user?",
  "Have you been part of a gangbang?",
  "Do you have a deep roster?",
  "Have you had more than 2 abortions?",
  "Were you not born in the US?",
  "Do you have a promiscuous past? (High body count)",
  "Are you super easy to get / have you cheated on another guy to be with someone?",
  "Do you have an OnlyFans?",
  "Were you / are you a stripper?",
  "Are you a party girl?",
  "Do you wear too much makeup?",
  "Do you NOT go to the gym?",
  "Have you had more than 3 body-altering surgeries?",
  "Do you jump from relationship to relationship?",
  "Are you unemployed?",
  "Do you drink a lot?",
  "Do you have a guy best friend or too many guy friends?",
  "Do you not have a car / can't drive? (SF exception)",
  "Do you have a tattoo of an ex on your body?",
  "Do you have an ex that committed suicide?",
  "Do you lack personal goals or interest in personal growth?",
  "Do you still live at home after the age of 25?",
  "Do you work in: Travel, Nursing, Bartending, or as a Flight Attendant?",
  "Have you been engaged or married more than 2 times?",
  "Have you never lived on your own for at least 2 years?",
  "Are you financially irresponsible? (Heavy debt or lack of work ethic)",
  "Did you become overly religious after 30?",
  "Do you have poor personal hygiene / neglect your living space?",
  "Do you dislike animals or are you rough with pets?",
  "Are you a hypocrite? (Holding others to standards you don't follow)",
  "Do you take zero accountability for your mistakes? (Gaslighting, playing victim)",
  "Do you bash all your exes and label them all as \"crazy\"?",
  "Do you talk about an ex constantly? (Unresolved feelings)",
  "Are you still in frequent contact with an ex without a clear reason?",
  "Do you have no long-term friendships?",
  "Do you try to isolate your partner from their family and friends?",
  "Do you move way too fast? (Talking marriage or kids within weeks)",
  "Do your partner's friends and family not like you?",
  "Do your parents have too much control over your life?",
  "Are you competitive with your partner? (Turning achievements into rivalry)",
  "Are you rude to service workers?",
  "Are you a pathological liar? (Even about small things)",
  "Do you have main character syndrome? (Acting entitled)",
  "Do you have severe jealousy over friends, family, or colleagues?",
  "Are you controlling? (Dictating what they wear or who they see)",
  "Do you have a victim mentality? (Never the problem in any situation)",
  "Do you have narcissistic tendencies? (Exaggerated self-importance)",
  "Do you have gambling issues?",
  "Have you been physically violent? (Hitting, pushing, breaking objects)",
  "Are you cruel?",
  "Are you petty?",
  "Are you constantly pessimistic? (Everything through a negative lens)",
  "Is your Instagram / Facebook public?",
  "Do you have 1500+ followers on social media?",
  "Do you hide your relationship on social media?",
  "Are you constantly hiding your phone screen / logging out of apps / clearing activity?",
  "Do you like or comment on thirst traps / suggestive content?",
  "Do you post constant selfies or dramatic content just for attention?",
  "Is your social media misleading about your real life?",
  "Do you have an unbalanced following/followers ratio?",
  "Do you still have exes on social media?",
  "Do you have more than 2 Instagram profiles?",
  "Do you have more highlights than posts on Instagram?",
  "Have you been on a private jet?",
  "Do you have more than 5 bikini pics on social media?",
  "Do you have lots of filtered pictures on social media?",
  "Have you been flown out to more than 5 exotic locations?",
  "Do you know where the cup holder is in a Porsche 911?",
  "Does your lifestyle not match your income? (Math not mathing)",
  "Do you give the silent treatment instead of talking through issues?",
  "Do you gaslight people? (Making them doubt their own reality)",
  "Do you lack empathy?",
  "Do you refuse to apologize or take personal accountability?",
  "Do you react with explosive rage to minor inconveniences?",
  "Are you emotionally volatile? (Hot and cold without warning)",
  "Do you trauma dump heavy personal history on the first few dates?",
  "Do you barely or never initiate texts or calls?",
  "Have you ever tested someone with a pregnancy scare prank?",
  "Do you call yourself an \"Alpha female\"?",
  "Did you only notice your partner when they became accomplished?",
  "Can you NOT cook?",
  "Can you NOT clean?",
  "Do you not eat sushi?",
  "Do you go to Vegas more than Kenny does?",
  "Do you use online dating apps?",
  "Do you have over 2000 contacts on your phone?",
  "Is your phone always on sleep / silent mode?",
  "Are your notifications turned off?",
  "Do you have more than 2 personal phones?",
  "Can you NOT do a P&L statement?",
  "Do you never offer to pay for a meal?",
  "Would you order A5 wagyu or caviar on a first date?",
  "Do you only eat at Michelin star restaurants?",
  "Do you refuse to do coffee or tea dates?",
  "Do you get flowers on your birthday from guys your partner doesn't know about?",
  "Have you been with a guy older than your dad?",
  "Do you ask your partner to pay for your flights / travel on girls' trips?",
  "Have you had sugar daddies?",
  "Have you been with 2 guys in less than 24 hours?",
]

export default questions
